# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python3.8/dist-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python3.8/dist-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/studia/sem6/ZPR/projekt/CEC2017-BlackBox-Ranking

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/studia/sem6/ZPR/projekt/CEC2017-BlackBox-Ranking

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/lib/python3.8/dist-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/lib/python3.8/dist-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/studia/sem6/ZPR/projekt/CEC2017-BlackBox-Ranking/CMakeFiles /mnt/d/studia/sem6/ZPR/projekt/CEC2017-BlackBox-Ranking//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/studia/sem6/ZPR/projekt/CEC2017-BlackBox-Ranking/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LIB

# Build rule for target.
LIB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LIB
.PHONY : LIB

# fast build rule for target.
LIB/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/build
.PHONY : LIB/fast

#=============================================================================
# Target rules for targets named APP

# Build rule for target.
APP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 APP
.PHONY : APP

# fast build rule for target.
APP/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/APP.dir/build.make CMakeFiles/APP.dir/build
.PHONY : APP/fast

app/main.o: app/main.cc.o
.PHONY : app/main.o

# target to build an object file
app/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/APP.dir/build.make CMakeFiles/APP.dir/app/main.cc.o
.PHONY : app/main.cc.o

app/main.i: app/main.cc.i
.PHONY : app/main.i

# target to preprocess a source file
app/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/APP.dir/build.make CMakeFiles/APP.dir/app/main.cc.i
.PHONY : app/main.cc.i

app/main.s: app/main.cc.s
.PHONY : app/main.s

# target to generate assembly for a file
app/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/APP.dir/build.make CMakeFiles/APP.dir/app/main.cc.s
.PHONY : app/main.cc.s

lib/src/ApiKeyManager.o: lib/src/ApiKeyManager.cc.o
.PHONY : lib/src/ApiKeyManager.o

# target to build an object file
lib/src/ApiKeyManager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/ApiKeyManager.cc.o
.PHONY : lib/src/ApiKeyManager.cc.o

lib/src/ApiKeyManager.i: lib/src/ApiKeyManager.cc.i
.PHONY : lib/src/ApiKeyManager.i

# target to preprocess a source file
lib/src/ApiKeyManager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/ApiKeyManager.cc.i
.PHONY : lib/src/ApiKeyManager.cc.i

lib/src/ApiKeyManager.s: lib/src/ApiKeyManager.cc.s
.PHONY : lib/src/ApiKeyManager.s

# target to generate assembly for a file
lib/src/ApiKeyManager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/ApiKeyManager.cc.s
.PHONY : lib/src/ApiKeyManager.cc.s

lib/src/DatabaseManager.o: lib/src/DatabaseManager.cc.o
.PHONY : lib/src/DatabaseManager.o

# target to build an object file
lib/src/DatabaseManager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/DatabaseManager.cc.o
.PHONY : lib/src/DatabaseManager.cc.o

lib/src/DatabaseManager.i: lib/src/DatabaseManager.cc.i
.PHONY : lib/src/DatabaseManager.i

# target to preprocess a source file
lib/src/DatabaseManager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/DatabaseManager.cc.i
.PHONY : lib/src/DatabaseManager.cc.i

lib/src/DatabaseManager.s: lib/src/DatabaseManager.cc.s
.PHONY : lib/src/DatabaseManager.s

# target to generate assembly for a file
lib/src/DatabaseManager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/DatabaseManager.cc.s
.PHONY : lib/src/DatabaseManager.cc.s

lib/src/FunctionManager.o: lib/src/FunctionManager.cc.o
.PHONY : lib/src/FunctionManager.o

# target to build an object file
lib/src/FunctionManager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/FunctionManager.cc.o
.PHONY : lib/src/FunctionManager.cc.o

lib/src/FunctionManager.i: lib/src/FunctionManager.cc.i
.PHONY : lib/src/FunctionManager.i

# target to preprocess a source file
lib/src/FunctionManager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/FunctionManager.cc.i
.PHONY : lib/src/FunctionManager.cc.i

lib/src/FunctionManager.s: lib/src/FunctionManager.cc.s
.PHONY : lib/src/FunctionManager.s

# target to generate assembly for a file
lib/src/FunctionManager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/FunctionManager.cc.s
.PHONY : lib/src/FunctionManager.cc.s

lib/src/HttpRequestHandler.o: lib/src/HttpRequestHandler.cc.o
.PHONY : lib/src/HttpRequestHandler.o

# target to build an object file
lib/src/HttpRequestHandler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/HttpRequestHandler.cc.o
.PHONY : lib/src/HttpRequestHandler.cc.o

lib/src/HttpRequestHandler.i: lib/src/HttpRequestHandler.cc.i
.PHONY : lib/src/HttpRequestHandler.i

# target to preprocess a source file
lib/src/HttpRequestHandler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/HttpRequestHandler.cc.i
.PHONY : lib/src/HttpRequestHandler.cc.i

lib/src/HttpRequestHandler.s: lib/src/HttpRequestHandler.cc.s
.PHONY : lib/src/HttpRequestHandler.s

# target to generate assembly for a file
lib/src/HttpRequestHandler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/HttpRequestHandler.cc.s
.PHONY : lib/src/HttpRequestHandler.cc.s

lib/src/JsonParser.o: lib/src/JsonParser.cc.o
.PHONY : lib/src/JsonParser.o

# target to build an object file
lib/src/JsonParser.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/JsonParser.cc.o
.PHONY : lib/src/JsonParser.cc.o

lib/src/JsonParser.i: lib/src/JsonParser.cc.i
.PHONY : lib/src/JsonParser.i

# target to preprocess a source file
lib/src/JsonParser.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/JsonParser.cc.i
.PHONY : lib/src/JsonParser.cc.i

lib/src/JsonParser.s: lib/src/JsonParser.cc.s
.PHONY : lib/src/JsonParser.s

# target to generate assembly for a file
lib/src/JsonParser.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LIB.dir/build.make CMakeFiles/LIB.dir/lib/src/JsonParser.cc.s
.PHONY : lib/src/JsonParser.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... APP"
	@echo "... LIB"
	@echo "... app/main.o"
	@echo "... app/main.i"
	@echo "... app/main.s"
	@echo "... lib/src/ApiKeyManager.o"
	@echo "... lib/src/ApiKeyManager.i"
	@echo "... lib/src/ApiKeyManager.s"
	@echo "... lib/src/DatabaseManager.o"
	@echo "... lib/src/DatabaseManager.i"
	@echo "... lib/src/DatabaseManager.s"
	@echo "... lib/src/FunctionManager.o"
	@echo "... lib/src/FunctionManager.i"
	@echo "... lib/src/FunctionManager.s"
	@echo "... lib/src/HttpRequestHandler.o"
	@echo "... lib/src/HttpRequestHandler.i"
	@echo "... lib/src/HttpRequestHandler.s"
	@echo "... lib/src/JsonParser.o"
	@echo "... lib/src/JsonParser.i"
	@echo "... lib/src/JsonParser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

